name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
    steps:
      # Checkout le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests with pytest
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q
          
  notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Simuler l'envoi de notification Slack (à adapter selon votre besoin)
      - name: Notify Slack
        run: echo "Notifying Slack... (simulation)"
